## TEST FUNCTION FOR AR

In [1]:
import numpy as np

In [57]:
# random array of 2 sequences shape L=3, q=2 (q is int 1 or 2, randomly generated)
L = 3
q = 2
seq_array = np.random.randint(0, q, (5, L)) 
N_seq =  seq_array
print(N_seq.shape)

(5, 3)


In [ ]:
# J tens of shape L,L,q,q
J = np.random.rand(L, L, q, q)
# select 2D array L*L by fixing q
J_2D = J[:, :, 0, 1]
print(J_2D.shape)
print(J_2D)

(3, 3)
[[0.63509365 0.50313626 0.07056875]
 [0.94023024 0.45825289 0.96119056]
 [0.100778   0.07118865 0.81446848]]


In [38]:

J_tens = J[k,:,aa,seq_array]
print(J_tens.shape)

(5, 3, 3)


In [39]:
def energy_position_k(k,aa, seq_array, J):
        mask= np.concatenate((np.ones((seq_array.shape[0],k+1)),np.zeros((seq_array.shape[0],L-k-1))),axis=1)
        print(mask.shape)
        sum_arr= np.einsum("nk,nk->n",mask,J[k,:,aa,seq_array])

In [95]:
def energy_position_k_loop_oneseq(k, aa, seq, J):
    print(seq.shape)
    e_vec = 0
    # same but vectorized
    for j in range(k):
        # J[k, j, aa, seq[j]] for all j<k
        e_vec += J[k, j, aa, seq[j]]
    #e_vec += np.sum(J[k, :k, aa, seq[:k]])
    return e_vec

def energy_position_k_loop(k, aa, seq_array, J):
    e = np.zeros(seq_array.shape[0])
    for i in range(seq_array.shape[0]):
        e[i] = energy_position_k_loop_oneseq(k, aa, seq_array[i], J)
    return e


In [ ]:
def energy_position_k_all(k, aa, seq_array, J):
    n_seq = seq_array.shape[0]
    # indices of positions < k
    idx = np.arange(k)

    # shape (n_seq, k)
    seq_sub = seq_array[:, idx]
    print(seq_sub.shape)

    # gather J[k, j, aa, seq_sub] for all j<k, seqs
    # this broadcasts: (k,) vs (n_seq, k)
    e = J[k, idx[None, :], aa, seq_sub]
    print(e.shape)

    # sum over positions <k, leaving (n_seq,)
    return e.sum(axis=1)

In [93]:
e = energy_position_k_loop(2, 0, seq_array, J)
ej = energy_position_k_all(2, 0, seq_array, J)
print(e)
print(ej)

(3,)
(3,)
(3,)
(3,)
(3,)
(5, 2)
(5, 2)
[0.38833693 0.75236807 0.7012286  0.75236807 0.7012286 ]
[0.14054995 0.75236807 0.78378477 0.75236807 0.78378477]


In [96]:
k=0
aa=0
enrj = energy_position_k_loop(k, aa, seq_array, J)
print(enrj)

ej = energy_position_k_all(k, aa, seq_array, J)
print(ej)

(3,)
(3,)
(3,)
(3,)
(3,)
[0. 0. 0. 0. 0.]
(5, 0)
(5, 0)
[0. 0. 0. 0. 0.]
